main_track/web/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('maintrack.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_track/web/maintrack/forms.py
import datetime
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from mt_library.entities.task import TaskStatus, TaskPriority
from mt_library.database.db_entities import Task
from mt_library.controllers.tasks_controller import create_task_controller
from mt_library.controllers.tags_controller import create_tags_controller
import mt_library.commands as commands
from tempus_dominus.widgets import DateTimePicker


class TaskForm(forms.Form):
    def __init__(self, user_id=None, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        tasks = commands.filter_tasks(create_task_controller(user_id, settings.MAIN_TRACK_DATABASE_PATH),
                                      (Task.user_id == user_id))
        tasks_tuple = [(task.id, task.title) for task in tasks]
        tags = commands.user_tags(create_tags_controller(user_id, settings.MAIN_TRACK_DATABASE_PATH))
        tags_tuple = [(tag.id, tag.name) for tag in tags]
        tasks_tuple.insert(0, ('', '---------'))
        tags_tuple.insert(0, ('', '---------'))

        self.fields['tag'] = forms.ChoiceField(choices=tags_tuple, required=False)
        self.fields['parent_id'] = forms.ChoiceField(choices=tasks_tuple, required=False)

    title = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'title': "Task's title"}))
    note = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'title': "Task's note"}))
    parent_id = forms.ChoiceField(required=False)
    assigned_user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    begin = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'minDate': (datetime.date.today()).strftime('%Y-%m-%d'),
                'useCurrent': True,
            }
        ), required=True
    )
    end = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'minDate': (datetime.date.today()).strftime('%Y-%m-%d'),
                'useCurrent': True,
            }
        ), required=True
    )
    status = forms.ChoiceField(choices=[(e.value, TaskStatus(e).name) for e in TaskStatus], required=False)
    tag = forms.ChoiceField(required=False)
    priority = forms.ChoiceField(choices=[(e.value, TaskPriority(e).name) for e in TaskPriority], required=False)


class RegularTaskForm(forms.Form):
    def __init__(self, user_id=None, *args, **kwargs):
        super(RegularTaskForm, self).__init__(*args, **kwargs)
        tasks = commands.filter_tasks(create_task_controller(user_id, settings.MAIN_TRACK_DATABASE_PATH),
                                      (Task.user_id == user_id))
        tasks_tuple = [(task.id, task.title) for task in tasks]
        tasks_tuple.insert(0, ('', '---------'))
        self.fields['template_task_id'] = forms.ChoiceField(choices=tasks_tuple, required=False)

    template_task_id = forms.ChoiceField(required=False)
    interval = forms.CharField(max_length=400)


class EventForm(forms.Form):
    def __init__(self, user_id=None, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        tasks = commands.filter_tasks(create_task_controller(user_id, settings.MAIN_TRACK_DATABASE_PATH),
                                      (Task.user_id == user_id))
        tasks_tuple = [(task.id, task.title) for task in tasks]
        tasks_tuple.insert(0, ('', '---------'))
        self.fields['template_task_id'] = forms.ChoiceField(choices=tasks_tuple, required=False)

    template_task_id = forms.ChoiceField(required=False)
    place = forms.CharField(max_length=400)


class TagForm(forms.Form):
    name = forms.CharField(max_length=100)

main_track/web/templates/events/all.html
{% extends 'base.html' %}
{% block title %}Events info{% endblock %}
{% block content %}
{% load tasks %}
{% load template_tasks %}
<form method="post" action="">
    {% csrf_token %}
    <h2 class="heading text-center">All events</h2>
    <table class="table" id="dtBasicExample">
        <thead class="thead-dark">
        <tr>
            <th><input type="checkbox"></th>
            <th class="th-sm">Task</th>
            <th class="th-sm">Place</th>
        </tr>
        </thead>
        <tbody>
        {% for event in events %}
        <tr>
            <td><input type="checkbox" name="checkbox" id="{{event.id}}"></td>
            <td>
                <a href="{% url 'detail_task' event.task_id %}">
                    {% get_template_task_title event.task_id event.user_id %}
                </a>
            </td>
            <td>{{event.place}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</form>
<script >
    $(document).ready(function () {
        var table = $('#dtBasicExample').DataTable({
            'columnDefs': [{
                    'targets': 0,
                    'checkboxes': {
                       'selectRow': true
                        }
                    }],
            'select': {
                    'style': 'multi'
                    },
            'dom': '<"toolbar">frtip',
            'order': [[1, 'asc']]
        });
        $("div.toolbar").html('<a href="{% url "new_event" %}"  class="btn btn-primary">New</a> <input type="submit" class="btn btn-dark" id="edit" name="_edit" disabled value="Edit"/> <input type="submit" class="btn btn-danger" id="delete" name="_delete" disabled value="Delete"/> ');
        $('#dtBasicExample tbody input[type="checkbox"]').change(function() {
            var count = $('#dtBasicExample tbody :input[type="checkbox"]:checked').length;
            if (this.checked){
                var data = table.row($(this).closest('tr')).data()[0];
                this.name="checkbox";
                var temp=data.split('id="')[1];
                this.value=temp.split('"')[0];
            }
            if (count > 0) {
                $('#delete').removeAttr('disabled');
                if (count == 1) {
                    $('#edit').removeAttr('disabled');
                }
                else {
                     $('#edit').attr('disabled', true);
                }
            }
            else {
                $('#delete').attr('disabled', true);
                $('#edit').attr('disabled', true);
            }
        });

    });
</script>
{% endblock %}

main_track/web/templates/events/detail.html
{% extends 'base.html' %}
{% block title %}Detail event{% endblock %}
{% block content %}
{% load bootstrap4 %}
{% load widget_tweaks %}

<div class="main-content" >
    <div class="form-basic">
       <div class="bg-dark form-title-row">
           <h2 class="text-center text-white">Event</h2>
       </div>
       {% if form.non_field_errors %}
       <div class="alert alert-danger" role="alert">
           {% for error in form.non_field_errors %}
           {{ error }}
           {% endfor %}
       </div>
       {% endif %}
       <form method="post"  id="regular">
           {% csrf_token %}
           <div class="form-group row">
               <label for="{{form.place.id_for_label}}" class="col-form-label col-sm-4">
                   {{ form.place.label }}
               </label>
               <div class="col-sm-1">
                   {{ form.place }}
               </div>
           </div>
           <div class="form-row">
               <input type="submit" style="color: white; margin: 0 auto" class="btn btn-primary" value="Save" />
           </div>
       </form>
    </div>
</div>
{% endblock %}

main_track/web/templates/events/new.html
{% extends 'base.html' %}
{% block title %}New event{% endblock %}
{% block content %}
{% load bootstrap4 %}
{% load widget_tweaks %}

<div class="main-content" >
    <div class="form-basic">
        <div class="bg-dark form-title-row">
            <h2 class="text-center text-white">New Event</h2>
        </div>
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        <a href="{% url 'new_task' %}">Create new task</a>
        <div style="margin: 20px"/>
        <form method="post"  id="regular" action="{% url 'new_event' %}">
            {% csrf_token %}
            <div class="form-group row" id="select_exist_task">
                <label for="{{form.template_task_id.id_for_label}}" class="col-form-label col-sm-4">
                    {{ form.template_task_id.label }}
                </label>
                <div class="col-sm-1">
                    {{form.template_task_id}}
                </div>
            </div>
            <div class="form-group row">
                <label for="{{form.interval.id_for_label}}" class="col-form-label col-sm-4">
                    {{ form.place.label }}
                </label>
                <div class="col-sm-1">
                    {{form.place}}
                </div>
            </div>
            <div class="form-row">
                <input type="submit" style="color: white; margin: 0 auto" class="btn btn-primary" value="Save" id="save_regular"/>
            </div>
        </form>
    </div>
</div>
<script>
 $(document).ready(function () {
    $('input[type=radio][name=radio]').click(function() {
        if (this.checked){
            if (this.id == 'select_radio') {
                 $('#id_template_task_id').attr('required', true);
                 $('#id_begin').removeAttr('required');
                 $('#id_end').removeAttr('required');
                 $('#select_exist_task').removeAttr('hidden');
                 $('#create_new_task').attr('hidden', true);
            }
            else if (this.id == 'create_radio') {
                $('#id_template_task_id').removeAttr('required');
                $('#id_begin').attr('required', true);
                $('#id_end').attr('required', true);
                $('#create_new_task').removeAttr('hidden');
                $('#select_exist_task').attr('hidden', true);
            }
         }
    });
 });
</script>
{% endblock %}